global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "cadvisor"
    static_configs:
      - targets: [ 'cadvisor:8080' ]

  - job_name: 'node-exporter'
    static_configs:
      - targets: [ 'node-exporter:9100' ]

  - job_name: 'backend'
    static_configs:
      - targets: [ 'host.docker.internal:8000' ,'3.35.125.66:8000']
